//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.UI.eCommerceWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eCommerceWS.eCommerceWebServiceSoap")]
    public interface eCommerceWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        eCommerce.UI.eCommerceWS.HelloWorldResponse HelloWorld(eCommerce.UI.eCommerceWS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.HelloWorldResponse> HelloWorldAsync(eCommerce.UI.eCommerceWS.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ad from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YasSoyle", ReplyAction="*")]
        eCommerce.UI.eCommerceWS.YasSoyleResponse YasSoyle(eCommerce.UI.eCommerceWS.YasSoyleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YasSoyle", ReplyAction="*")]
        System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.YasSoyleResponse> YasSoyleAsync(eCommerce.UI.eCommerceWS.YasSoyleRequest request);
        
        // CODEGEN: Generating message contract since element name getUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsers", ReplyAction="*")]
        eCommerce.UI.eCommerceWS.getUsersResponse getUsers(eCommerce.UI.eCommerceWS.getUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.getUsersResponse> getUsersAsync(eCommerce.UI.eCommerceWS.getUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public eCommerce.UI.eCommerceWS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(eCommerce.UI.eCommerceWS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public eCommerce.UI.eCommerceWS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(eCommerce.UI.eCommerceWS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YasSoyleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YasSoyle", Namespace="http://tempuri.org/", Order=0)]
        public eCommerce.UI.eCommerceWS.YasSoyleRequestBody Body;
        
        public YasSoyleRequest() {
        }
        
        public YasSoyleRequest(eCommerce.UI.eCommerceWS.YasSoyleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YasSoyleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int dogumYili;
        
        public YasSoyleRequestBody() {
        }
        
        public YasSoyleRequestBody(string ad, int dogumYili) {
            this.ad = ad;
            this.dogumYili = dogumYili;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YasSoyleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YasSoyleResponse", Namespace="http://tempuri.org/", Order=0)]
        public eCommerce.UI.eCommerceWS.YasSoyleResponseBody Body;
        
        public YasSoyleResponse() {
        }
        
        public YasSoyleResponse(eCommerce.UI.eCommerceWS.YasSoyleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YasSoyleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string YasSoyleResult;
        
        public YasSoyleResponseBody() {
        }
        
        public YasSoyleResponseBody(string YasSoyleResult) {
            this.YasSoyleResult = YasSoyleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsers", Namespace="http://tempuri.org/", Order=0)]
        public eCommerce.UI.eCommerceWS.getUsersRequestBody Body;
        
        public getUsersRequest() {
        }
        
        public getUsersRequest(eCommerce.UI.eCommerceWS.getUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUsersRequestBody {
        
        public getUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public eCommerce.UI.eCommerceWS.getUsersResponseBody Body;
        
        public getUsersResponse() {
        }
        
        public getUsersResponse(eCommerce.UI.eCommerceWS.getUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<eCommerce.UI.eCommerceWS.User> getUsersResult;
        
        public getUsersResponseBody() {
        }
        
        public getUsersResponseBody(System.Collections.Generic.List<eCommerce.UI.eCommerceWS.User> getUsersResult) {
            this.getUsersResult = getUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface eCommerceWebServiceSoapChannel : eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eCommerceWebServiceSoapClient : System.ServiceModel.ClientBase<eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap>, eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap {
        
        public eCommerceWebServiceSoapClient() {
        }
        
        public eCommerceWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public eCommerceWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eCommerceWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eCommerceWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eCommerce.UI.eCommerceWS.HelloWorldResponse eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap.HelloWorld(eCommerce.UI.eCommerceWS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            eCommerce.UI.eCommerceWS.HelloWorldRequest inValue = new eCommerce.UI.eCommerceWS.HelloWorldRequest();
            inValue.Body = new eCommerce.UI.eCommerceWS.HelloWorldRequestBody();
            eCommerce.UI.eCommerceWS.HelloWorldResponse retVal = ((eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.HelloWorldResponse> eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap.HelloWorldAsync(eCommerce.UI.eCommerceWS.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.HelloWorldResponse> HelloWorldAsync() {
            eCommerce.UI.eCommerceWS.HelloWorldRequest inValue = new eCommerce.UI.eCommerceWS.HelloWorldRequest();
            inValue.Body = new eCommerce.UI.eCommerceWS.HelloWorldRequestBody();
            return ((eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eCommerce.UI.eCommerceWS.YasSoyleResponse eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap.YasSoyle(eCommerce.UI.eCommerceWS.YasSoyleRequest request) {
            return base.Channel.YasSoyle(request);
        }
        
        public string YasSoyle(string ad, int dogumYili) {
            eCommerce.UI.eCommerceWS.YasSoyleRequest inValue = new eCommerce.UI.eCommerceWS.YasSoyleRequest();
            inValue.Body = new eCommerce.UI.eCommerceWS.YasSoyleRequestBody();
            inValue.Body.ad = ad;
            inValue.Body.dogumYili = dogumYili;
            eCommerce.UI.eCommerceWS.YasSoyleResponse retVal = ((eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap)(this)).YasSoyle(inValue);
            return retVal.Body.YasSoyleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.YasSoyleResponse> eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap.YasSoyleAsync(eCommerce.UI.eCommerceWS.YasSoyleRequest request) {
            return base.Channel.YasSoyleAsync(request);
        }
        
        public System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.YasSoyleResponse> YasSoyleAsync(string ad, int dogumYili) {
            eCommerce.UI.eCommerceWS.YasSoyleRequest inValue = new eCommerce.UI.eCommerceWS.YasSoyleRequest();
            inValue.Body = new eCommerce.UI.eCommerceWS.YasSoyleRequestBody();
            inValue.Body.ad = ad;
            inValue.Body.dogumYili = dogumYili;
            return ((eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap)(this)).YasSoyleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eCommerce.UI.eCommerceWS.getUsersResponse eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap.getUsers(eCommerce.UI.eCommerceWS.getUsersRequest request) {
            return base.Channel.getUsers(request);
        }
        
        public System.Collections.Generic.List<eCommerce.UI.eCommerceWS.User> getUsers() {
            eCommerce.UI.eCommerceWS.getUsersRequest inValue = new eCommerce.UI.eCommerceWS.getUsersRequest();
            inValue.Body = new eCommerce.UI.eCommerceWS.getUsersRequestBody();
            eCommerce.UI.eCommerceWS.getUsersResponse retVal = ((eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap)(this)).getUsers(inValue);
            return retVal.Body.getUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.getUsersResponse> eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap.getUsersAsync(eCommerce.UI.eCommerceWS.getUsersRequest request) {
            return base.Channel.getUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<eCommerce.UI.eCommerceWS.getUsersResponse> getUsersAsync() {
            eCommerce.UI.eCommerceWS.getUsersRequest inValue = new eCommerce.UI.eCommerceWS.getUsersRequest();
            inValue.Body = new eCommerce.UI.eCommerceWS.getUsersRequestBody();
            return ((eCommerce.UI.eCommerceWS.eCommerceWebServiceSoap)(this)).getUsersAsync(inValue);
        }
    }
}
